[system]
servicePort = ":6002"

[log]
logLevel=1 # 日志级别，0:debug, 1:info, 2:warn, 3:error, 4:fatal
logFlag=6 # 设置log格式,多选项可相加，1:显示调用路径，2:现在文件名，4:显示函数名，8:error日志程序退出

[sql]
writeConn =  "root:hexinpass001@tcp(192.168.2.200:3306)/welfare?charset=utf8&parseTime=true"
maxConn = 150
maxIdleConn = 100

[pushInfo]
    [pushInfo.android]
    appKey = "bVUHL9VGkb7v2mMG89BsrA"
    appId = "A6XeYnzWWS6cYpg40gdi72"
    masterSecret = "WEcTyMoo2n97A0Pdv2zV14"

    [pushInfo.ios]
    model = "pro"
    password = ""
    pem = "cert.pem"
    package = "com.welfare.platform"