[system]
servicePort = ":6002"

[log]
logLevel=1 # 日志级别，0:debug, 1:info, 2:warn, 3:error, 4:fatal
logFlag=6 # 设置log格式,多选项可相加，1:显示调用路径，2:现在文件名，4:显示函数名，8:error日志程序退出

[sql]
writeConn =  "root:hexinpass001@tcp(192.168.2.200:3306)/jiaotou?charset=utf8&parseTime=true"
maxConn = 150
maxIdleConn = 100

[pushInfo]
    [pushInfo.android]
    appKey = "VCrFi2bMsV5GoJgfde6fW5"
    appId = "fC1PHUhCyY5DcTmwXtrIc9"
    masterSecret = "Fi1j7mPUyp6LXQHoBii2C9"

    [pushInfo.ios]
    isDev = false
    password = ""
    pem = "jt-apns-dis.pem"
    package = "com.scst.tifamily"